// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class ToNativeParams {
  ToNativeParams({
    required this.message,
    required this.times,
  });

  String message;

  int times;

  Object encode() {
    return <Object?>[
      message,
      times,
    ];
  }

  static ToNativeParams decode(Object result) {
    result as List<Object?>;
    return ToNativeParams(
      message: result[0]! as String,
      times: result[1]! as int,
    );
  }
}

class ToFlutterParams {
  ToFlutterParams({
    required this.message,
    required this.batteryLevel,
  });

  String message;

  double batteryLevel;

  Object encode() {
    return <Object?>[
      message,
      batteryLevel,
    ];
  }

  static ToFlutterParams decode(Object result) {
    result as List<Object?>;
    return ToFlutterParams(
      message: result[0]! as String,
      batteryLevel: result[1]! as double,
    );
  }
}

class _TestNativeApiCodec extends StandardMessageCodec {
  const _TestNativeApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ToFlutterParams) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is ToNativeParams) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return ToFlutterParams.decode(readValue(buffer)!);
      case 129: 
        return ToNativeParams.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TestNativeApi {
  /// Constructor for [TestNativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TestNativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _TestNativeApiCodec();

  final String __pigeon_messageChannelSuffix;

  Future<ToFlutterParams> sendMessage(ToNativeParams params) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.flutter_practice.TestNativeApi.sendMessage$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[params]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as ToFlutterParams?)!;
    }
  }
}

abstract class TestFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = StandardMessageCodec();

  void onGotBatteryLevel(double batteryLevel);

  static void setUp(TestFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_practice.TestFlutterApi.onGotBatteryLevel$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_practice.TestFlutterApi.onGotBatteryLevel was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final double? arg_batteryLevel = (args[0] as double?);
          assert(arg_batteryLevel != null,
              'Argument for dev.flutter.pigeon.flutter_practice.TestFlutterApi.onGotBatteryLevel was null, expected non-null double.');
          try {
            api.onGotBatteryLevel(arg_batteryLevel!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
